// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/trackhunter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackHunterService_AddFingerprint_FullMethodName    = "/trackhunter.TrackHunterService/AddFingerprint"
	TrackHunterService_ListFingerprints_FullMethodName  = "/trackhunter.TrackHunterService/ListFingerprints"
	TrackHunterService_GetFingerprint_FullMethodName    = "/trackhunter.TrackHunterService/GetFingerprint"
	TrackHunterService_DeleteFingerprint_FullMethodName = "/trackhunter.TrackHunterService/DeleteFingerprint"
)

// TrackHunterServiceClient is the client API for TrackHunterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackHunterServiceClient interface {
	AddFingerprint(ctx context.Context, in *AddFingerprintRequest, opts ...grpc.CallOption) (*AddFingerprintResponse, error)
	ListFingerprints(ctx context.Context, in *ListFingerprintsRequest, opts ...grpc.CallOption) (*ListFingerprintsResponse, error)
	GetFingerprint(ctx context.Context, in *GetFingerprintRequest, opts ...grpc.CallOption) (*GetFingerprintResponse, error)
	DeleteFingerprint(ctx context.Context, in *DeleteFingerprintRequest, opts ...grpc.CallOption) (*DeleteFingerprintResponse, error)
}

type trackHunterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackHunterServiceClient(cc grpc.ClientConnInterface) TrackHunterServiceClient {
	return &trackHunterServiceClient{cc}
}

func (c *trackHunterServiceClient) AddFingerprint(ctx context.Context, in *AddFingerprintRequest, opts ...grpc.CallOption) (*AddFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFingerprintResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_AddFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHunterServiceClient) ListFingerprints(ctx context.Context, in *ListFingerprintsRequest, opts ...grpc.CallOption) (*ListFingerprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFingerprintsResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_ListFingerprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHunterServiceClient) GetFingerprint(ctx context.Context, in *GetFingerprintRequest, opts ...grpc.CallOption) (*GetFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFingerprintResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_GetFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHunterServiceClient) DeleteFingerprint(ctx context.Context, in *DeleteFingerprintRequest, opts ...grpc.CallOption) (*DeleteFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFingerprintResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_DeleteFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackHunterServiceServer is the server API for TrackHunterService service.
// All implementations must embed UnimplementedTrackHunterServiceServer
// for forward compatibility.
type TrackHunterServiceServer interface {
	AddFingerprint(context.Context, *AddFingerprintRequest) (*AddFingerprintResponse, error)
	ListFingerprints(context.Context, *ListFingerprintsRequest) (*ListFingerprintsResponse, error)
	GetFingerprint(context.Context, *GetFingerprintRequest) (*GetFingerprintResponse, error)
	DeleteFingerprint(context.Context, *DeleteFingerprintRequest) (*DeleteFingerprintResponse, error)
	mustEmbedUnimplementedTrackHunterServiceServer()
}

// UnimplementedTrackHunterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackHunterServiceServer struct{}

func (UnimplementedTrackHunterServiceServer) AddFingerprint(context.Context, *AddFingerprintRequest) (*AddFingerprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFingerprint not implemented")
}
func (UnimplementedTrackHunterServiceServer) ListFingerprints(context.Context, *ListFingerprintsRequest) (*ListFingerprintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFingerprints not implemented")
}
func (UnimplementedTrackHunterServiceServer) GetFingerprint(context.Context, *GetFingerprintRequest) (*GetFingerprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFingerprint not implemented")
}
func (UnimplementedTrackHunterServiceServer) DeleteFingerprint(context.Context, *DeleteFingerprintRequest) (*DeleteFingerprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFingerprint not implemented")
}
func (UnimplementedTrackHunterServiceServer) mustEmbedUnimplementedTrackHunterServiceServer() {}
func (UnimplementedTrackHunterServiceServer) testEmbeddedByValue()                            {}

// UnsafeTrackHunterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackHunterServiceServer will
// result in compilation errors.
type UnsafeTrackHunterServiceServer interface {
	mustEmbedUnimplementedTrackHunterServiceServer()
}

func RegisterTrackHunterServiceServer(s grpc.ServiceRegistrar, srv TrackHunterServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrackHunterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackHunterService_ServiceDesc, srv)
}

func _TrackHunterService_AddFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).AddFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_AddFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).AddFingerprint(ctx, req.(*AddFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHunterService_ListFingerprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFingerprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).ListFingerprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_ListFingerprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).ListFingerprints(ctx, req.(*ListFingerprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHunterService_GetFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).GetFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_GetFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).GetFingerprint(ctx, req.(*GetFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHunterService_DeleteFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).DeleteFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_DeleteFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).DeleteFingerprint(ctx, req.(*DeleteFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackHunterService_ServiceDesc is the grpc.ServiceDesc for TrackHunterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackHunterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trackhunter.TrackHunterService",
	HandlerType: (*TrackHunterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFingerprint",
			Handler:    _TrackHunterService_AddFingerprint_Handler,
		},
		{
			MethodName: "ListFingerprints",
			Handler:    _TrackHunterService_ListFingerprints_Handler,
		},
		{
			MethodName: "GetFingerprint",
			Handler:    _TrackHunterService_GetFingerprint_Handler,
		},
		{
			MethodName: "DeleteFingerprint",
			Handler:    _TrackHunterService_DeleteFingerprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trackhunter.proto",
}
