// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/trackhunter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                // Raw audio data (WAV/PCM/MP3/etc.)
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`                        // "wav", "pcm", "mp3"
	SampleRate    uint32                 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 44100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_trackhunter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *AudioChunk) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Track metadata
type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // internal UUID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`       // optional
	Duration      float32                `protobuf:"fixed32,5,opt,name=duration,proto3" json:"duration,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_proto_trackhunter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{1}
}

func (x *Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Track) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// Identify a song from audio
type IdentifySongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         *AudioChunk            `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifySongRequest) Reset() {
	*x = IdentifySongRequest{}
	mi := &file_proto_trackhunter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifySongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifySongRequest) ProtoMessage() {}

func (x *IdentifySongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifySongRequest.ProtoReflect.Descriptor instead.
func (*IdentifySongRequest) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{2}
}

func (x *IdentifySongRequest) GetAudio() *AudioChunk {
	if x != nil {
		return x.Audio
	}
	return nil
}

type IdentifySongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 → 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifySongResponse) Reset() {
	*x = IdentifySongResponse{}
	mi := &file_proto_trackhunter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifySongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifySongResponse) ProtoMessage() {}

func (x *IdentifySongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifySongResponse.ProtoReflect.Descriptor instead.
func (*IdentifySongResponse) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{3}
}

func (x *IdentifySongResponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *IdentifySongResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Add new fingerprints to DB
type AddFingerprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Track                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Audio         *AudioChunk            `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"` // full reference audio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFingerprintRequest) Reset() {
	*x = AddFingerprintRequest{}
	mi := &file_proto_trackhunter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFingerprintRequest) ProtoMessage() {}

func (x *AddFingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFingerprintRequest.ProtoReflect.Descriptor instead.
func (*AddFingerprintRequest) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{4}
}

func (x *AddFingerprintRequest) GetMetadata() *Track {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AddFingerprintRequest) GetAudio() *AudioChunk {
	if x != nil {
		return x.Audio
	}
	return nil
}

type AddFingerprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFingerprintResponse) Reset() {
	*x = AddFingerprintResponse{}
	mi := &file_proto_trackhunter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFingerprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFingerprintResponse) ProtoMessage() {}

func (x *AddFingerprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFingerprintResponse.ProtoReflect.Descriptor instead.
func (*AddFingerprintResponse) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{5}
}

func (x *AddFingerprintResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddFingerprintResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Retrieve full track info
type GetTrackInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackInfoRequest) Reset() {
	*x = GetTrackInfoRequest{}
	mi := &file_proto_trackhunter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackInfoRequest) ProtoMessage() {}

func (x *GetTrackInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTrackInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{6}
}

func (x *GetTrackInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTrackInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackInfoResponse) Reset() {
	*x = GetTrackInfoResponse{}
	mi := &file_proto_trackhunter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackInfoResponse) ProtoMessage() {}

func (x *GetTrackInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackhunter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTrackInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_trackhunter_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrackInfoResponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

var File_proto_trackhunter_proto protoreflect.FileDescriptor

const file_proto_trackhunter_proto_rawDesc = "" +
	"\n" +
	"\x17proto/trackhunter.proto\x12\vtrackhunter\"]\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\rR\n" +
	"sampleRate\"y\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x02R\bduration\"D\n" +
	"\x13IdentifySongRequest\x12-\n" +
	"\x05audio\x18\x01 \x01(\v2\x17.trackhunter.AudioChunkR\x05audio\"`\n" +
	"\x14IdentifySongResponse\x12(\n" +
	"\x05track\x18\x01 \x01(\v2\x12.trackhunter.TrackR\x05track\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"v\n" +
	"\x15AddFingerprintRequest\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.trackhunter.TrackR\bmetadata\x12-\n" +
	"\x05audio\x18\x02 \x01(\v2\x17.trackhunter.AudioChunkR\x05audio\"L\n" +
	"\x16AddFingerprintResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x13GetTrackInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x14GetTrackInfoResponse\x12(\n" +
	"\x05track\x18\x01 \x01(\v2\x12.trackhunter.TrackR\x05track2\x99\x02\n" +
	"\x12TrackHunterService\x12S\n" +
	"\fIdentifySong\x12 .trackhunter.IdentifySongRequest\x1a!.trackhunter.IdentifySongResponse\x12Y\n" +
	"\x0eAddFingerprint\x12\".trackhunter.AddFingerprintRequest\x1a#.trackhunter.AddFingerprintResponse\x12S\n" +
	"\fGetTrackInfo\x12 .trackhunter.GetTrackInfoRequest\x1a!.trackhunter.GetTrackInfoResponseB\x0fZ\r./proto;protob\x06proto3"

var (
	file_proto_trackhunter_proto_rawDescOnce sync.Once
	file_proto_trackhunter_proto_rawDescData []byte
)

func file_proto_trackhunter_proto_rawDescGZIP() []byte {
	file_proto_trackhunter_proto_rawDescOnce.Do(func() {
		file_proto_trackhunter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trackhunter_proto_rawDesc), len(file_proto_trackhunter_proto_rawDesc)))
	})
	return file_proto_trackhunter_proto_rawDescData
}

var file_proto_trackhunter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_trackhunter_proto_goTypes = []any{
	(*AudioChunk)(nil),             // 0: trackhunter.AudioChunk
	(*Track)(nil),                  // 1: trackhunter.Track
	(*IdentifySongRequest)(nil),    // 2: trackhunter.IdentifySongRequest
	(*IdentifySongResponse)(nil),   // 3: trackhunter.IdentifySongResponse
	(*AddFingerprintRequest)(nil),  // 4: trackhunter.AddFingerprintRequest
	(*AddFingerprintResponse)(nil), // 5: trackhunter.AddFingerprintResponse
	(*GetTrackInfoRequest)(nil),    // 6: trackhunter.GetTrackInfoRequest
	(*GetTrackInfoResponse)(nil),   // 7: trackhunter.GetTrackInfoResponse
}
var file_proto_trackhunter_proto_depIdxs = []int32{
	0, // 0: trackhunter.IdentifySongRequest.audio:type_name -> trackhunter.AudioChunk
	1, // 1: trackhunter.IdentifySongResponse.track:type_name -> trackhunter.Track
	1, // 2: trackhunter.AddFingerprintRequest.metadata:type_name -> trackhunter.Track
	0, // 3: trackhunter.AddFingerprintRequest.audio:type_name -> trackhunter.AudioChunk
	1, // 4: trackhunter.GetTrackInfoResponse.track:type_name -> trackhunter.Track
	2, // 5: trackhunter.TrackHunterService.IdentifySong:input_type -> trackhunter.IdentifySongRequest
	4, // 6: trackhunter.TrackHunterService.AddFingerprint:input_type -> trackhunter.AddFingerprintRequest
	6, // 7: trackhunter.TrackHunterService.GetTrackInfo:input_type -> trackhunter.GetTrackInfoRequest
	3, // 8: trackhunter.TrackHunterService.IdentifySong:output_type -> trackhunter.IdentifySongResponse
	5, // 9: trackhunter.TrackHunterService.AddFingerprint:output_type -> trackhunter.AddFingerprintResponse
	7, // 10: trackhunter.TrackHunterService.GetTrackInfo:output_type -> trackhunter.GetTrackInfoResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_trackhunter_proto_init() }
func file_proto_trackhunter_proto_init() {
	if File_proto_trackhunter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trackhunter_proto_rawDesc), len(file_proto_trackhunter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trackhunter_proto_goTypes,
		DependencyIndexes: file_proto_trackhunter_proto_depIdxs,
		MessageInfos:      file_proto_trackhunter_proto_msgTypes,
	}.Build()
	File_proto_trackhunter_proto = out.File
	file_proto_trackhunter_proto_goTypes = nil
	file_proto_trackhunter_proto_depIdxs = nil
}
