// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/trackhunter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackHunterService_IdentifySong_FullMethodName   = "/trackhunter.TrackHunterService/IdentifySong"
	TrackHunterService_AddFingerprint_FullMethodName = "/trackhunter.TrackHunterService/AddFingerprint"
	TrackHunterService_GetTrackInfo_FullMethodName   = "/trackhunter.TrackHunterService/GetTrackInfo"
)

// TrackHunterServiceClient is the client API for TrackHunterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackHunterServiceClient interface {
	IdentifySong(ctx context.Context, in *IdentifySongRequest, opts ...grpc.CallOption) (*IdentifySongResponse, error)
	AddFingerprint(ctx context.Context, in *AddFingerprintRequest, opts ...grpc.CallOption) (*AddFingerprintResponse, error)
	GetTrackInfo(ctx context.Context, in *GetTrackInfoRequest, opts ...grpc.CallOption) (*GetTrackInfoResponse, error)
}

type trackHunterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackHunterServiceClient(cc grpc.ClientConnInterface) TrackHunterServiceClient {
	return &trackHunterServiceClient{cc}
}

func (c *trackHunterServiceClient) IdentifySong(ctx context.Context, in *IdentifySongRequest, opts ...grpc.CallOption) (*IdentifySongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentifySongResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_IdentifySong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHunterServiceClient) AddFingerprint(ctx context.Context, in *AddFingerprintRequest, opts ...grpc.CallOption) (*AddFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFingerprintResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_AddFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHunterServiceClient) GetTrackInfo(ctx context.Context, in *GetTrackInfoRequest, opts ...grpc.CallOption) (*GetTrackInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackInfoResponse)
	err := c.cc.Invoke(ctx, TrackHunterService_GetTrackInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackHunterServiceServer is the server API for TrackHunterService service.
// All implementations must embed UnimplementedTrackHunterServiceServer
// for forward compatibility.
type TrackHunterServiceServer interface {
	IdentifySong(context.Context, *IdentifySongRequest) (*IdentifySongResponse, error)
	AddFingerprint(context.Context, *AddFingerprintRequest) (*AddFingerprintResponse, error)
	GetTrackInfo(context.Context, *GetTrackInfoRequest) (*GetTrackInfoResponse, error)
	mustEmbedUnimplementedTrackHunterServiceServer()
}

// UnimplementedTrackHunterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackHunterServiceServer struct{}

func (UnimplementedTrackHunterServiceServer) IdentifySong(context.Context, *IdentifySongRequest) (*IdentifySongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentifySong not implemented")
}
func (UnimplementedTrackHunterServiceServer) AddFingerprint(context.Context, *AddFingerprintRequest) (*AddFingerprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFingerprint not implemented")
}
func (UnimplementedTrackHunterServiceServer) GetTrackInfo(context.Context, *GetTrackInfoRequest) (*GetTrackInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackInfo not implemented")
}
func (UnimplementedTrackHunterServiceServer) mustEmbedUnimplementedTrackHunterServiceServer() {}
func (UnimplementedTrackHunterServiceServer) testEmbeddedByValue()                            {}

// UnsafeTrackHunterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackHunterServiceServer will
// result in compilation errors.
type UnsafeTrackHunterServiceServer interface {
	mustEmbedUnimplementedTrackHunterServiceServer()
}

func RegisterTrackHunterServiceServer(s grpc.ServiceRegistrar, srv TrackHunterServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrackHunterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackHunterService_ServiceDesc, srv)
}

func _TrackHunterService_IdentifySong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifySongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).IdentifySong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_IdentifySong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).IdentifySong(ctx, req.(*IdentifySongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHunterService_AddFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).AddFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_AddFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).AddFingerprint(ctx, req.(*AddFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHunterService_GetTrackInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHunterServiceServer).GetTrackInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHunterService_GetTrackInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHunterServiceServer).GetTrackInfo(ctx, req.(*GetTrackInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackHunterService_ServiceDesc is the grpc.ServiceDesc for TrackHunterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackHunterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trackhunter.TrackHunterService",
	HandlerType: (*TrackHunterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IdentifySong",
			Handler:    _TrackHunterService_IdentifySong_Handler,
		},
		{
			MethodName: "AddFingerprint",
			Handler:    _TrackHunterService_AddFingerprint_Handler,
		},
		{
			MethodName: "GetTrackInfo",
			Handler:    _TrackHunterService_GetTrackInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trackhunter.proto",
}
